### ISSUE TITLE
Feat: As a user I should be able to see the quiz app from anywhere with a browser

### ISSUE THREAD

**Issue by imtiaz101325** [imtiaz101325/hyf-cohort47-browsers-quizical-minds#2]
We will need to deploy our quiz app. 

This can be done with GitHub pages to keep things simple.

Read up on GH Pages [here](https://pages.github.com/).

Once you have good idea deploy the app.

**Comment by BenGumaan** [comment]
I'll do this task.

**Comment by BenGumaan** [comment]
I deployed the website to GitHub pages.
